### ISSUE TITLE
Please support x86 processor

### ISSUE THREAD

**Issue by tringuyenhoaiphuong** [woxihuannisja/Bangcle#2]
Today, lot of android devices and emulators are x86 based processor. It would be great if Bangcle support this processor type.

Thank you for your great tool!

**Comment by lpcdma** [comment]
https://github.com/lpcdma/Bangcle add x86 support

**Comment by tringuyenhoaiphuong** [comment]
> https://github.com/lpcdma/Bangcle add x86 support

Works perfectly! Thank you very much!

**Comment by WolfHami** [comment]
Plz help read last issue I have 2 pc some error coming help me plz
